name: fetch_data_py

on:
  workflow_dispatch:   # Manual trigger
  schedule:
    # Runs every 15 minutes between 4:00 and 10:15 UTC (9:30am–3:45pm IST), Mon–Fri
    - cron: "0,15,30,45 4-10 * * 1-5"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python data_fetch.py   # ⬅️ change to your actual filename

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md *.db || true
          if ! git diff --cached --quiet; then
            git commit -m "Automated data update: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          else
            echo "No changes to commit"
          fi
