name: Fetch NIFTY50 Data

on:
  schedule:
    # Run every 15 minutes during NSE trading hours (04:00–10:15 UTC = 9:30–15:45 IST)
    - cron: "*/15 4-10 * * 1-5"
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data fetch script
        run: |
          python data_fetch.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add nifty50_top20.db README.md
          git commit -m "Automated data update: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"

          # Make sure we have latest main branch
          git pull --rebase origin main || true

          # Push with rebase (safe fast-forward)
          git push origin main

