name: Fetch NIFTY50 Data

on:
  # schedule:
  #   - cron: "*/15 4-10 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: fetch-nifty50
  cancel-in-progress: true

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data fetch script
        run: |
          python data_fetch.py

      - name: Pull latest changes
        run: git pull --rebase origin main
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f nifty50_top20.db README.md data_fetch.log
          git commit -m "Automated data update: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git pull --rebase origin main
          git push
