name: Fetch NIFTY50 Data

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: "0,15,30,45 4-10 * * 1-5"   # every 15 mins between 9:30am-3:45pm IST

permissions:
  contents: write

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install yfinance pandas tabulate pytz

      - name: Run data fetch script
        run: python data_fetch.py

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add README.md nifty50_top20.db data_fetch.log
          git commit -m "Automated data update: $(date -u)"
          git push
