name: Manual NIFTY50 Data Fetch

on:
  workflow_dispatch:  # Manual trigger

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas tabulate pytz

      - name: Run data fetch script
        run: python data_fetch.py

      - name: Commit and push README and DB updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md nifty50_top20.db data_fetch.log
          git commit -m "Update stock data and snapshot [CI skip]" || echo "No changes to commit"
          git push
